---
# https://kubernetes.io/docs/tasks/tools/install-kubectl/
- name: Update repositories cache and install "apt-transport-https" package
  apt:
    name: apt-transport-https
#    update_cache: yes


- name: Create the file /etc/apt/sources.list.d/kubernetes.list
  apt_repository:
    filename: kubernetes
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Update repositories cache and install "kubectl" package
  apt:
    name: "kubectl={{ kube_version }}-00"
    update_cache: yes

- name: create the kubeconfig folder
  file:
    path: /root/kthw
    state: directory
    mode: 0755

- name: set up profile file for setting up kubectl
  copy: 
    content: |
      export KUBECONFIG=/root/kthw/kubeconfigs/admin.kubeconfig
      source <(kubectl completion bash)
    dest: /etc/profile.d/kubectl.sh