---
# the kube-controller-manager.kubeconfig file content is identical across all master nodes. 

# this is 4 command shell-script. 
# first command adds cluster info and gives it a name
# second command sets username+cert login credentials, and gives it special reserved name
# third command - creates a context and adds in the cluster+user profiles to it. 
# fourth command - a kubeconfig file can contain settings for multiple contexts (which in turn can store info about other clusters + user-creds).
#                  so here we say what is the default context, if it's not specified in the kubectl command line. 
- name: Create the kube-controller-manager.kubeconfig file.  
  shell: |
    /usr/bin/kubectl config set-cluster codingbee_cluster \
    --certificate-authority=/vagrant/kube_cache/tls/01_ca/ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443  \
    --kubeconfig=kubeconfigs/kube-controller-manager.kubeconfig

    /usr/bin/kubectl config set-credentials system:kube-controller-manager \
    --client-certificate=/vagrant/kube_cache/tls/03_controller_manager_certs/kube-controller-manager.pem \
    --client-key=/vagrant/kube_cache/tls/03_controller_manager_certs/kube-controller-manager-key.pem \
    --embed-certs=true \
    --kubeconfig=kubeconfigs/kube-controller-manager.kubeconfig

    /usr/bin/kubectl config set-context default \
    --cluster=codingbee_cluster \
    --user=system:kube-controller-manager \
    --kubeconfig=kubeconfigs/kube-controller-manager.kubeconfig

    /usr/bin/kubectl config use-context default --kubeconfig=kubeconfigs/kube-controller-manager.kubeconfig
  args:
    chdir: /root/kthw
    creates: /root/kthw/kubeconfigs/kube-controller-manager.kubeconfig