---
# the kube-scheduler.kubeconfig file content is identical across all master nodes. 
- name: Create the kube-scheduler.kubeconfig file.  
  shell: |
    /usr/bin/kubectl config set-cluster codingbee_cluster \
    --certificate-authority=/vagrant/kube_cache/tls/01_ca/ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443  \
    --kubeconfig=kubeconfigs/kube-scheduler.kubeconfig

    /usr/bin/kubectl config set-credentials system:kube-scheduler \
    --client-certificate=/vagrant/kube_cache/tls/05_kube_scheduler_certs/kube-scheduler.pem \
    --client-key=/vagrant/kube_cache/tls/05_kube_scheduler_certs/kube-scheduler-key.pem \
    --embed-certs=true \
    --kubeconfig=kubeconfigs/kube-scheduler.kubeconfig

    /usr/bin/kubectl config set-context default \
    --cluster=codingbee_cluster \
    --user=system:kube-scheduler \
    --kubeconfig=kubeconfigs/kube-scheduler.kubeconfig

    /usr/bin/kubectl config use-context default --kubeconfig=kubeconfigs/kube-scheduler.kubeconfig
  args:
    chdir: /root/kthw
    creates: /root/kthw/kubeconfigs/kube-scheduler.kubeconfig
