---
# the admin.kubeconfig file content is identical across all master nodes. 
- name: Create the admin.kubeconfig file.  
  shell: |
    /usr/bin/kubectl config set-cluster codingbee_cluster \
    --certificate-authority=/vagrant/kube_cache/tls/01_ca/ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443  \
    --kubeconfig=kubeconfigs/admin.kubeconfig

    /usr/bin/kubectl config set-credentials admin \
    --client-certificate=/vagrant/kube_cache/tls/02_admin_client_certs/admin.pem \
    --client-key=/vagrant/kube_cache/tls/02_admin_client_certs/admin-key.pem \
    --embed-certs=true \
    --kubeconfig=kubeconfigs/admin.kubeconfig

    /usr/bin/kubectl config set-context default \
    --cluster=codingbee_cluster \
    --user=admin \
    --kubeconfig=kubeconfigs/admin.kubeconfig

    /usr/bin/kubectl config use-context default --kubeconfig=kubeconfigs/admin.kubeconfig
  args:
    chdir: /root/kthw
    creates: /root/kthw/kubeconfigs/admin.kubeconfig

