---


# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md

- name: Copy across the service-account-csr.json file
  copy:
    src: tls/07_service_account_key_pair/service-account-csr.json
    dest: /vagrant/kube_cache/tls/07_service_account_key_pair/service-account-csr.json
    mode: 0644



- name: This command affectively generates the CA related files 
  shell: |
    /usr/local/bin/cfssl gencert \
    -ca=/vagrant/kube_cache/tls/01_ca/ca.pem \
    -ca-key=/vagrant/kube_cache/tls/01_ca/ca-key.pem \
    -config=/vagrant/kube_cache/tls/01_ca/ca-config.json \
    -profile=kubernetes \
    service-account-csr.json | /usr/local/bin/cfssljson -bare service-account 
  args:
    chdir: /vagrant/kube_cache/tls/07_service_account_key_pair
    creates: /vagrant/kube_cache/tls/07_service_account_key_pair/service-account-key.pem
# it also creates
# - /vagrant/kube_cache/tls/03_controller_manager_certs/service-account.pem
# - /vagrant/kube_cache/tls/03_controller_manager_certs/service-account.csr


 