---

# https://app.pluralsight.com/player?course=kubernetes-installation-configuration-fundamentals&author=anthony-nocentino&name=edf35e15-3c12-441a-bcbc-254691db32d3&clip=7&mode=live

# this is same as running:
# apt-get update
# apt-get install -y xxx xxx
- name: Update cache and then install packages
  apt:
#    update_cache: yes
#    cache_valid_time: 864000 #One day
    name: "{{ packages }}"
  vars:
    packages:
      - bash-completion
      - tree
