---

- name: Create the kubelet kubeconfig file.  
  shell: |
    kubectl config set-cluster codingbee_cluster \
    --certificate-authority=/vagrant/kube_cache/tls/01_ca/ca.pem \
    --embed-certs=true \
    --server=https://{{ kubemaster_ip_address }}:6443 \
    --kubeconfig={{ ansible_hostname | lower }}.kubeconfig  || exit 1

    kubectl config set-credentials system:node:{{ ansible_hostname | lower }} \
    --client-certificate=/root/kthw/tls/worker.pem \
    --client-key=/root/kthw/tls/worker-key.pem \
    --embed-certs=true \
    --kubeconfig={{ansible_hostname | lower }}.kubeconfig   || exit 1

    kubectl config set-context default \
    --cluster=codingbee_cluster \
    --user=system:node:{{ ansible_hostname | lower }} \
    --kubeconfig={{ ansible_hostname | lower }}.kubeconfig  || exit 1

    kubectl config use-context default --kubeconfig={{ ansible_hostname | lower }}.kubeconfig
  args:
    chdir: /root/kthw/kubeconfigs
    creates: /root/kthw/kubeconfigs/{{ ansible_hostname | lower }}.kubeconfig