---
# the kube-proxy.kubeconfig file content is identical across all worker nodes. 
- name: Create the kube-proxy.kubeconfig file.  
  shell: |
    kubectl config set-cluster codingbee_cluster \
    --certificate-authority=/vagrant/kube_cache/tls/01_ca/ca.pem \
    --embed-certs=true \
    --server=https://{{ kubemaster_ip_address }}:6443 \
    --kubeconfig=kubeconfigs/kube-proxy.kubeconfig

    kubectl config set-credentials system:kube-proxy \
    --client-certificate=/vagrant/kube_cache/tls/04_kube_proxy_certs/kube-proxy.pem \
    --client-key=/vagrant/kube_cache/tls/04_kube_proxy_certs/kube-proxy-key.pem \
    --embed-certs=true \
    --kubeconfig=kubeconfigs/kube-proxy.kubeconfig

    kubectl config set-context default \
    --cluster=codingbee_cluster \
    --user=system:kube-proxy \
    --kubeconfig=kubeconfigs/kube-proxy.kubeconfig

    kubectl config use-context default --kubeconfig=kubeconfigs/kube-proxy.kubeconfig
  args:
    chdir: /root/kthw
    creates: /root/kthw/kubeconfigs/kube-proxy.kubeconfig
