---


- name: copy kube-controller-manager files to lib folder folder
  copy: 
    src: /root/kthw/kubeconfigs/kube-controller-manager.kubeconfig 
    dest: /var/lib/kubernetes
    remote_src: yes
    mode: 0555
  notify: restart kube-controller-manager


- name: Generate the kube-controller-manager.service systemd file. 
  template: 
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    mode: 0755
  notify: restart kube-controller-manager

- name: start kube-controller-manager service daemon 
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: kube-controller-manager

